### ISSUE TITLE
bug on Flutter1.5.4-hotfix.2

### ISSUE THREAD

**Issue by xiongdi9456** [diegoveloper/flutter_direct_select#2]
Hello, I run your Demo on Flutter1.5.4-hotfix.2 and I can't select any item.
Error Message:

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...

registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

Built build/app/outputs/apk/debug/app-debug.apk.

I/CameraManagerGlobal(26534): Connecting to camera service

D/EGL_emulation(26534): eglMakeCurrent: 0x9fe852a0: ver 3 0 (tinfo 0x9fe83230)

I/flutter (26534): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════

I/flutter (26534): The following NoSuchMethodError was thrown while handling a gesture:

I/flutter (26534): The method 'reverse' was called on null.

I/flutter (26534): Receiver: null

I/flutter (26534): Tried calling: reverse(Instance of 'OverlayEntry')

I/flutter (26534):

I/flutter (26534): When the exception was thrown, this was the stack:

I/flutter (26534): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:50:5)

I/flutter (26534): #1      _DirectSelectState._removeOverlay 

I/flutter (26534): #2      _DirectSelectState.build.<anonymous closure> 

I/flutter (26534): #3      DragGestureRecognizer.didStopTrackingLastPointer.<anonymous closure> 

I/flutter (26534): #4      GestureRecognizer.invokeCallback 

I/flutter (26534): #5      DragGestureRecognizer.didStopTrackingLastPointer 

I/flutter (26534): #6      OneSequenceGestureRecognizer.stopTrackingPointer 

I/flutter (26534): #7      OneSequenceGestureRecognizer.stopTrackingIfPointerNoLongerDown 

I/flutter (26534): #8      DragGestureRecognizer.handleEvent 

I/flutter (26534): #9      PointerRouter._dispatch 

I/flutter (26534): #10     PointerRouter.route 

I/flutter (26534): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent 

I/flutter (26534): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent 

I/flutter (26534): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent 

I/flutter (26534): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue 

I/flutter (26534): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket 

I/flutter (26534): #19     _invoke1  (dart:ui/hooks.dart:233:10)

I/flutter (26534): #20     _dispatchPointerDataPacket  (dart:ui/hooks.dart:154:5)

I/flutter (26534): (elided 3 frames from package dart:async)

I/flutter (26534):

I/flutter (26534): Handler: onEnd

I/flutter (26534): Recognizer:

I/flutter (26534):   VerticalDragGestureRecognizer#f6314(debugOwner: GestureDetector, start behavior: start)

I/flutter (26534): ════════════════════════════════════════════════════════════════════════════════════════════════════

D/EGL_emulation(26534): eglMakeCurrent: 0x9d53bee0: ver 3 0 (tinfo 0x9b81e8f0)


```

**Comment by diegoveloper** [comment]
I'm running Flutter 1.5.8 • channel dev  without any problems iOS/Android.

**Comment by xiongdi9456** [comment]
My emulator Android version is Android 8.0 -API 26, could you test it again?

**Comment by diegoveloper** [comment]
try using your device or ios simulator
